global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: /metrics

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: /metrics

  - job_name: 'resume-service'
    static_configs:
      - targets: ['resume-service:3002']
    metrics_path: /metrics

  - job_name: 'template-service'
    static_configs:
      - targets: ['template-service:3003']
    metrics_path: /metrics

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:3004']
    metrics_path: /metrics

  - job_name: 'blog-service'
    static_configs:
      - targets: ['blog-service:3005']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

